# Generated by Django 4.0.4 on 2023-01-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stack',
        ),
    ]
